# Generated by Django 4.2 on 2023-04-09 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Password must be at least 8 characters long and contain at least one uppercase letter, one lowercase letter, and one digit', regex='^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)[A-Za-z\\d@$!%*?&]{8,}$')])),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
